#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: girb [options]"

  opts.on("-d", "--debug", "Enable debug output") do
    options[:debug] = true
  end

  opts.on("-h", "--help", "Show this help") do
    puts opts
    exit
  end
end.parse!

ENV["GIRB_DEBUG"] = "1" if options[:debug]

require "irb"

# Load girb and provider
require "girb"

if ENV["GIRB_PROVIDER"]
  begin
    require ENV["GIRB_PROVIDER"]
  rescue LoadError
    warn "[girb] Failed to load provider: #{ENV["GIRB_PROVIDER"]}"
  end
else
  warn "[girb] No provider specified. Set GIRB_PROVIDER environment variable."
  warn "[girb]   Example: GIRB_PROVIDER=girb-ruby_llm girb"
end

IRB.start
